---
- name: Ensure Pip is installed.
  package:
    name: python3-pip
    state: present
  become: true

- name: install pip docker
  pip:
    name: docker

- name: install pip docker-compose
  pip:
    name: docker-compose

- name: Config volume exists
  file:
    path: "{{ hexaa_backend_host_volume }}/config"