---
- name: Ensure network exists
  docker_network:
    name: "{{ docker_network_name_backend }}"
    state: present

- name: start memcached
  docker_container:
    name: memcached
    image: "memcached"
    networks:
      - name: "{{ docker_network_name_backend }}"


- name: start entity id list generator container
  docker_container:
    name: hexaa-service-entityids-generator
    image: hexaaproject/hexaa-service-entityids-generator
    volumes:
      - "{{ config_dir.path }}/hexaa_entityids.yml:/tmp/hexaa_entityids.yml"
    env:
      METADATA_SOURCE_URLS: "{{ HEXAA_BACKEND_METADATA_SOURCE_URLS }}"
      TARGET_FILE_PATH: /tmp/hexaa_entityids.yml
      UPDATE_INTERVAL_MINUTES: "60"
    restart: yes
  when: (HEXAA_BACKEND_METADATA_SOURCE_URLS != "" and HEXAA_BACKEND_METADATA_SOURCE_URLS is not none)


- name: start hexaa-backend
  docker_container:
    name: hexaa-backend
    image: "{{ docker_image_name_backend }}:{{ docker_image_tag_backend }}"
    networks:
      - name: "{{ docker_network_name_backend }}"
    volumes:
      - "{{ config_dir.path }}:/opt/hexaa-backend/app/config/site:ro"
      - "{{ log_dir.path }}:/opt/hexaa-backend/app/logs"
      # export for the web container
      - /opt/hexaa-backend/web
    env:
      HEXAA_BACKEND_DATABASE_HOST: "{{ HEXAA_BACKEND_DATABASE_HOST }}"
      HEXAA_BACKEND_DATABASE_PORT: "{{ HEXAA_BACKEND_DATABASE_PORT }}"

- name: create ssp config directory
  tempfile:
    state: directory
  register: ssp_config_dir
  tags: [ssp]
- name: create simplesamlphp-config from template
  template:
    src: simplesamlphp-config.php.j2
    dest: "{{ ssp_config_dir.path }}/config.php"
  tags: [ssp]
- name: create simplesamlphp-attributeauthority-hosted from template
  template:
    src: simplesamlphp-attributeauthority-hosted.php.j2
    dest: "{{ ssp_config_dir.path }}/attributeauthority-hosted.php"
  tags: [ssp]


- name: start ssp-aa container
  docker_container:
    name: hexaa-backend-ssp-aa
    image: hexaaproject/ssp-aa
    #image: solazs/ssp-aa-php-fpm
    networks:
      - name: "{{ docker_network_name_backend }}"
    volumes:
      - "{{ ssp_config_dir.path }}/config.php:/opt/simplesamlphp/config/config.php:ro"
      - "{{ ssp_config_dir.path }}/attributeauthority-hosted.php:/opt/simplesamlphp/metadata/attributeauthority-hosted.php:ro"
      - "{{ SSP_CERT_PATH }}:/opt/simplesamlphp/cert:ro"
      - /opt/simplesamlphp/www
  tags: [ssp]

- name: start hexaa-backend-web
  tags: [web]
  docker_container:
    name: hexaa-backend-web
    image: nginx
    #auto_remove: yes
    ports:
      - "81:80"
      - "8443:8443"
    networks:
      - name: "{{ docker_network_name_backend }}"
    volumes_from:
      - hexaa-backend
      - hexaa-backend-ssp-aa
    volumes:
      - "{{ nginx_conf.path }}:/etc/nginx/conf.d/default.conf:ro"
      - "{{ SSP_CERT_PATH }}:/opt/simplesamlphp/cert:ro"
