---
- name: Ensure network exists
  docker_network:
    name: "{{ docker_network_name_backend }}"
    state: present

- name: start memcached
  docker_container:
    name: memcached
    image: "memcached"
    networks:
      - name: "{{ docker_network_name_backend }}"
    pull: yes
    restart_policy: "{{ docker_restart_policy }}"


- name: start entity id list generator container
  docker_container:
    name: hexaa-service-entityids-generator
    image: hexaaproject/hexaa-service-entityids-generator
    networks:
      - name: "{{ docker_network_name_backend }}"
    volumes:
      - "{{ config_dir.path }}/site/hexaa_entityids.yml:/tmp/hexaa_entityids.yml"
    env:
      METADATA_SOURCE_URLS: "{{ HEXAA_BACKEND_METADATA_SOURCE_URLS }}"
      TARGET_FILE_PATH: /tmp/hexaa_entityids.yml
      UPDATE_INTERVAL_MINUTES: "60"
    pull: yes
    restart_policy: "{{ docker_restart_policy }}"
    restart: yes
  when: (HEXAA_BACKEND_METADATA_SOURCE_URLS != "" and HEXAA_BACKEND_METADATA_SOURCE_URLS is not none)


- name: start hexaa-backend
  docker_container:
    name: hexaa-backend
    image: "{{ docker_image_name_backend }}:{{ docker_image_tag_backend }}"
    networks:
      - name: "{{ docker_network_name_backend }}"
    volumes:
      - "{{ config_dir.path }}/site:/opt/hexaa-backend/app/config/site:ro"
      - "{{ log_dir.path }}:/opt/hexaa-backend/app/logs"
      - "{{ config_dir.path }}/hooks:/opt/hexaa-backend-hooks"
      # export for the web container
      - /opt/hexaa-backend/web
    env:
      HEXAA_BACKEND_DATABASE_HOST: "{{ HEXAA_BACKEND_DATABASE_HOST }}"
      HEXAA_BACKEND_DATABASE_PORT: "{{ HEXAA_BACKEND_DATABASE_PORT }}"
    pull: yes
    restart_policy: "{{ docker_restart_policy }}"
    restart: yes


- name: start ssp-aa container
  docker_container:
    name: hexaa-backend-ssp-aa
    image: hexaaproject/ssp-aa
    networks:
      - name: "{{ docker_network_name_backend }}"
    volumes:
      - "{{ config_dir.path }}/ssp/config.php:/opt/simplesamlphp/config/config.php:ro"
      - "{{ config_dir.path }}/ssp/attributeauthority-hosted.php:/opt/simplesamlphp/metadata/attributeauthority-hosted.php:ro"
      - "{{ config_dir.path }}/ssp/module_aa.php:/opt/simplesamlphp/config/module_aa.php:ro"
      - "{{ SSP_CERT_PATH }}:/opt/simplesamlphp/cert:ro"
      # export for the web container
      - /opt/simplesamlphp/www
    pull: yes
    restart_policy: "{{ docker_restart_policy }}"
  tags: [ssp]

- name: start hexaa-backend-web
  tags: [web]
  docker_container:
    name: hexaa-backend-web
    image: nginx
    ports:
      - "81:80"
      - "8443:8443"
    networks:
      - name: "{{ docker_network_name_backend }}"
    volumes_from:
      - hexaa-backend
      - hexaa-backend-ssp-aa
    volumes:
      - "{{ config_dir.path }}/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "{{ SSP_CERT_PATH }}:/opt/simplesamlphp/cert:ro"
    pull: yes
    restart_policy: "{{ docker_restart_policy }}"
