---
- name: Ensure network exists
  docker_network:
    name: "{{ docker_network_name }}"
    state: present

- name: start memcached
  docker_container:
    name: memcached
    image: "memcached"
    networks:
      - name: "{{ docker_network_name }}"

- name: stop hexaa-backend
  docker_container:
    name: hexaa-backend
    state: absent

- name: start hexaa-backend
  docker_container:
    name: hexaa-backend
    image: hexaaproject/hexaa-backend:for-dev-env-variables
    # TODO command, csak hogy ne szálljon el
    command: "tail -f /dev/null"
    ports:
      - "81:80"
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - {{ hexaa_backend_host_volume }}/config/paramteres.yml:/var/www/TODO
