---
- name: include environment
  include_tasks: environment.yml
  tags: [backend]

- name: include database
  include_tasks: database.yml
  tags: [backend]

- name: include hexaa-backend
  include_tasks: hexaa-backend.yml
  tags: [backend]
